name: Hello CI Job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Say Hello from CI
        run: echo "✅ Hello from GitHub Actions CI pipeline!"
